language: r
warnings_are_errors: true
sudo: false
cache: packages

r_binary_packages:
  - Rcpp
  - RcppArmadillo
  - testthat
  - mgcv

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"

script:
  - make install
  - make check
  - make test
